'use client';
import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import Head from 'next/head';
import BusinessTable from "./table";
import { poppins700 } from '../app/fonts';
import { toast } from "react-toastify";

export default function Business() {
  const { data: session } = useSession();
  const [businesses, setBusinesses] = useState([]);

  useEffect(() => {
    const fetchBusinesses = async () => {
      try {
        const res = await fetch("/api/business/get-business-list", {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        });

        const data = await res.json();

        if (data.success) {
          setBusinesses(data.businesses);
        } else {
          toast.error(data.error);
        }
      } catch (error) {
        toast.error(error.message);
      }
    };

    if (session?.user?.email) {
      fetchBusinesses();
    }
  }, [session]);

  const handleApproveBusiness = async (businessUserId, approve) => {
    try {
      const res = await fetch("/api/business/approve-business", {
        method: "POST",
        body: JSON.stringify({
          userId: session?.user?.id,
          businessUserId,
          approve
        }),
        headers: {
          "Content-Type": "application/json",
        },
      });
      const data = await res.json();

      if (!data.success) {
        return toast.error(data.error);
      }
      setBusinesses(prevBusinesses => prevBusinesses.map(business =>
        business._id === businessUserId ? { ...business, isProfileApproved: approve } : business
      ));
      toast.success(data.message);
    } catch (e) {
      toast.error(e.message);
    }
  };

  return (
    <div>
      <Head>
        <title>Business Table</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col bg-gray-100 px-2">
        <div className={`${poppins700.className} mt-7 mb-6 text-[40px] font-black`}>
            Business Details
        </div>
        <div className='w-full lg:pr-6'>
         <BusinessTable rows={businesses} onApprove={handleApproveBusiness} />
        </div>
        
      </main>
    </div>
  );
}
